OpenVINO extension
openvinotoolkit/sd-webui-openvino pull request #1
Opened 2024-08-26 17:20 UTC by mengbingrock

### to do:

- [x] some code is from sd-control-net extension, need to say it .

- [x]  provide way to backup and restore original unet forward.

- [x]  controlnet fallback

- [x]  move utils functions into a separate file

- [x] improve it according to python style guide (https://google.github.io/styleguide/pyguide.html) (use some tools to vscode extension)

- [x]  improve article

**TODO:**
- [x] codestyle 
- [x] remove commented lines
- [x] test for vae
- [x] remove controlnet code

2024-08-26 17:37 UTC, likholat commented
@mengbingrock we should also add a Readme file with the description of this extension.

2024-08-26 17:42 UTC, mengbingrock commented
> @mengbingrock we should also add a Readme file with the description of this extension.

Thank you Anna for your remind, I'll add it today

2024-08-29 10:00 UTC, likholat commented
@mengbingrock please convert this request to "Ready for review" when it's ready.

2024-09-16 11:24 UTC, likholat commented on README.md
> +
Extra empty lines in this file

2024-09-16 11:24 UTC, likholat commented on install.py
> +def install_requirements(file_path='requirements.txt'):
If there a reason why we should parse the requirements file? Why can't we just use `pip install -r requirements.txt` ?

2024-09-16 11:24 UTC, likholat commented on metadata.ini
> +
Extra empty lines in this file

2024-09-16 11:24 UTC, likholat commented on install.py
> +def git_clone(url, dir, name, commithash=None):
Why do we need this method? Can't find the usage...

2024-09-16 11:24 UTC, likholat commented on scripts/RESRGAN.py
> +#import sd_hijack_autoencoder  # noqa: F401
Looks like we don't need these lines any more

2024-09-16 11:24 UTC, likholat commented on scripts/RESRGAN.py
> +        #scaler_data = UpscalerData("LDSR", None, self)
Looks like we don't need these lines any more

2024-09-16 11:24 UTC, likholat commented on scripts/global_state_openvino.py
> +OV_df_pipe = None # OpenVINO diffusers pipeline
Unused variable?

2024-09-16 11:24 UTC, likholat commented on scripts/global_state_openvino.py
> +OV_df_vae = None # vae diffusers model
```suggestion
ov_df_vae = None # vae diffusers model
```

2024-09-16 11:24 UTC, likholat commented on scripts/global_state_openvino.py
> +df_pipe = None # pipeline from single file of diffusers
Unused variable?

2024-09-16 11:24 UTC, likholat commented on scripts/openvino.py
> +        # to do: add feature to fallback default vae after replacement
```suggestion
        # TODO: add feature to fallback default vae after replacement
```

2024-09-16 11:24 UTC, likholat commented on scripts/openvino.py
> +            print('no custom vae loaded')
Please use `logging` module instead of print for the entire project: https://realpython.com/python-logging/

2024-09-16 11:24 UTC, likholat commented on scripts/openvino.py
> +script_callbacks.on_model_loaded(refiner_cb_fn)
Please use autopep8 formatter to format the code (for the entire project): https://code.visualstudio.com/docs/python/formatting

2024-09-16 11:24 UTC, likholat commented on scripts/utils_ov.py
> +        # to do: fix multiple seeds in x y z plot or prompt matrix
```suggestion
        # TODO: fix multiple seeds in x y z plot or prompt matrix
```

2024-09-16 11:24 UTC, likholat commented on scripts/openvino.py
> +        #refiner_ckpt.change(refiner_ckpt_change, refiner_ckpt)
Please remove all commented out unnecessary lines of code in the project files

2024-09-16 11:24 UTC, likholat commented on scripts/openvino.py
> +from scripts.utils_ov import mark_prompt_context, unmark_prompt_context, POSITIVE_MARK_TOKEN, NEGATIVE_MARK_TOKEN, MARK_EPS, get_control
Please move all imports to the beginning of the file

2024-09-16 11:24 UTC, likholat commented on scripts/openvino.py
> +            print('[OV] sd 1.5 detected')
Why only `1.5` version?

2024-09-16 11:24 UTC, likholat commented on scripts/openvino.py
> +                print('x min and max:', torch.min(x), torch.max(x)) #  tensor(-13.3997) tensor(11.1092)
uninformative comments

2024-09-16 11:24 UTC, likholat commented on scripts/openvino.py
> +            # Need to ensure that weights that have been modified before and are not present anymore are reset.
```suggestion
            # TODO: Need to ensure that weights that have been modified before and are not present anymore are reset.
```

2024-09-16 11:24 UTC, likholat commented on scripts/openvino.py
> +            print('[OV] load sd1 or sd2 pipeline')
```suggestion
            print('[OV] load sd pipeline')
```

2024-09-16 11:24 UTC, likholat commented on scripts/openvino.py
> +        ov_model.vae = pipes['diffusers'].vae.to("cpu")
Why there is no `openvino` backend for VAE model there?
Why are we using `OV_df_vae` variable for VAE model later? Shouldn't we use `ov_model.vae` for this model?

2024-09-16 11:24 UTC, likholat commented on scripts/openvino.py
> +    def deactivate(self):
This method does nothing

2024-09-16 11:25 UTC, likholat commented
@cavusmustafa please add your review

2024-09-16 22:00 UTC, mengbingrock commented on README.md
> +
Removed, Thanks

2024-09-16 22:01 UTC, mengbingrock commented on install.py
> +def install_requirements(file_path='requirements.txt'):
now used only 1 line to do the work:
```
launch.run(f"pip install -r {req}", f"Install requirements for OpenVINO",
               f"Error Install dependents for OpenVINO, extension will not be enabled", live = default_command_live)
```

2024-09-16 22:01 UTC, mengbingrock commented on metadata.ini
> +
removed, thanks

2024-09-16 22:01 UTC, mengbingrock commented on install.py
> +def git_clone(url, dir, name, commithash=None):
removed, thanks

2024-09-16 22:02 UTC, mengbingrock commented on scripts/RESRGAN.py
> +#import sd_hijack_autoencoder  # noqa: F401
removed, thanks

2024-09-16 22:02 UTC, mengbingrock commented on scripts/openvino.py
> +                print('x min and max:', torch.min(x), torch.max(x)) #  tensor(-13.3997) tensor(11.1092)
removed, thanks

2024-09-16 22:02 UTC, mengbingrock commented on scripts/openvino.py
> +            # Need to ensure that weights that have been modified before and are not present anymore are reset.
changed, Thanks

2024-09-16 22:03 UTC, mengbingrock commented on scripts/openvino.py
> +            print('[OV] load sd1 or sd2 pipeline')
changed, thanks

2024-09-16 22:04 UTC, mengbingrock commented on scripts/openvino.py
> +        ov_model.vae = pipes['diffusers'].vae.to("cpu")
changed according to review:
```
ov_model.vae = pipes['diffusers'].vae.to("cpu")

if loaded_vae_file is not None:
    logging.info('  hook the vae')
    ov_model.vae = AutoencoderKL.from_single_file(loaded_vae_file, local_files_only=True)
else:
    ov_model.vae = pipes['diffusers'].vae.to("cpu")
ov_model.vae.decode = torch.compile(ov_model.vae.decode, backend="openvino", options = opt)
```

2024-09-16 22:06 UTC, mengbingrock commented on scripts/openvino.py
> +    def deactivate(self):
added destructor
```
logging.info(' deactivate called')
del globals_state['openvino']
del globals_state['diffusers']
gc.collect()
globals_state['openvino'] = None
globals_state['diffusers'] = None

logging.info(' deactivate finished')
```

2024-09-16 22:06 UTC, mengbingrock commented on scripts/RESRGAN.py
> +        #scaler_data = UpscalerData("LDSR", None, self)
removed, thanks

2024-09-16 22:06 UTC, mengbingrock commented on scripts/global_state_openvino.py
> +OV_df_pipe = None # OpenVINO diffusers pipeline
removed

2024-09-16 22:06 UTC, mengbingrock commented on scripts/global_state_openvino.py
> +OV_df_vae = None # vae diffusers model
removed

2024-09-16 22:07 UTC, mengbingrock commented on scripts/global_state_openvino.py
> +df_pipe = None # pipeline from single file of diffusers
removed

2024-09-16 22:09 UTC, mengbingrock commented on scripts/openvino.py
> +            print('no custom vae loaded')
change `print` to `logging.info`.

2024-09-16 22:10 UTC, mengbingrock commented on scripts/openvino.py
> +script_callbacks.on_model_loaded(refiner_cb_fn)
Working on it...

2024-09-16 22:10 UTC, mengbingrock commented on scripts/openvino.py
> +        #refiner_ckpt.change(refiner_ckpt_change, refiner_ckpt)
removed, thanks

2024-09-16 22:11 UTC, mengbingrock commented on scripts/openvino.py
> +from scripts.utils_ov import mark_prompt_context, unmark_prompt_context, POSITIVE_MARK_TOKEN, NEGATIVE_MARK_TOKEN, MARK_EPS, get_control
done, thanks

2024-09-16 22:11 UTC, mengbingrock commented on scripts/openvino.py
> +            print('[OV] sd 1.5 detected')
changed to 'standard sd, not sd-xl', thanks

2024-09-17 08:57 UTC, likholat commented on scripts/openvino.py
> +script_callbacks.on_model_loaded(refiner_cb_fn)
Probably this can help: https://code.visualstudio.com/docs/python/formatting

2024-09-17 11:32 UTC, likholat commented on README.md
> +![Preview](imgs/preview.png)
```suggestion

![Preview](imgs/preview.png)
```

2024-09-17 11:32 UTC, likholat commented on README.md
> +## Installation
```suggestion

## Installation
```

2024-09-17 11:32 UTC, likholat commented on README.md
> +![Install](imgs/install1.png)
```suggestion

![Install](imgs/install1.png)
```

2024-09-17 11:32 UTC, likholat commented on README.md
> +![Install](imgs/install2.png)
```suggestion

![Install](imgs/install2.png)
```

2024-09-17 11:32 UTC, likholat commented on README.md
> +## Features
```suggestion

## Features
```

2024-09-17 11:32 UTC, likholat commented on README.md
> +
Remove empty lines at the end of the file

2024-09-17 11:32 UTC, likholat commented on install.py
> +               f"Error Install dependents for OpenVINO, extension will not be enabled", live = default_command_live)
```suggestion
               f"Error: OpenVINO dependencies were not installed correctly, OpenVINO extension will not be enabled", live = default_command_live)
```

2024-09-17 11:32 UTC, likholat commented on scripts/openvino.py
> +            logging.info('  finished unloading model')
Do we need these 2 extra spaces at the beginning of the message? Sometimes we have them, sometimes not

2024-09-17 11:32 UTC, likholat commented on scripts/openvino.py
> +        if loaded_vae_file is not None:
Now we have 2 code blocks with VAE model compilation. Which one is relevant?
This is the first one

2024-09-17 11:32 UTC, likholat commented on scripts/openvino.py
>              if OV_df_vae is None:
This is the second one. Do we need them both?

2024-09-17 11:33 UTC, likholat commented on scripts/openvino.py
> +            #model_data.sd_model = None
Do we need these commented lines?

2024-09-17 11:38 UTC, likholat commented on scripts/openvino.py
> +        #refiner_ckpt.change(refiner_ckpt_change, refiner_ckpt)
We still have the huge block of commented code above. Why do we need it?

2024-09-17 11:38 UTC, likholat commented on scripts/openvino.py
> +            #except Exception as e:
Please uncomment or remove this `try-except` code block.

2024-09-22 19:30 UTC, mengbingrock commented on README.md
> +
removed, thanks

2024-09-22 19:31 UTC, mengbingrock commented on scripts/openvino.py
> +            logging.info('  finished unloading model')
removed, thanks

2024-09-24 09:14 UTC, likholat requested changes

2024-09-24 09:14 UTC, likholat commented on scripts/openvino.py
> +                control_model = torch.compile(pipes['openvino'].controlnet, backend = 'openvino', options = opt)  # ControlNetModel.from_single_file('./extensions/sd-webui-controlnet/models/control_v
Do we need this comment?

2024-09-24 09:14 UTC, likholat commented on scripts/utils_ov.py
> +def unmark_prompt_context(x):
Looks like this code was copied from controlnet: https://github.com/Mikubill/sd-webui-controlnet/blob/56cec5b2958edf3b1807b7e7b2b1b5186dbd2f81/scripts/hook.py#L81

2024-09-24 09:14 UTC, likholat commented on scripts/utils_ov.py
> +def prompt_context_is_marked(x):
This code was copied from controlnet : https://github.com/Mikubill/sd-webui-controlnet/blob/main/scripts/hook.py

2024-09-24 09:15 UTC, likholat commented
@cavusmustafa please add your review

2024-09-24 09:18 UTC, likholat commented on scripts/openvino.py
> +        #self.configs = configs
please remove this commented line

2024-09-24 09:20 UTC, likholat commented on scripts/openvino.py
> +            if True: #df_pipe.do_classifier_free_guidance:
Why do we need this `if`? It's always true...

This code was copied from: https://github.com/instantX-research/InstantID/blob/2145b67f9607da6234702063692330185f374486/pipeline_stable_diffusion_xl_instantid_full.py#L1032

2024-09-24 09:30 UTC, likholat commented on scripts/utils_ov.py
> +import torch
Not sure if we need this file, can't we just import these methods?

2024-09-26 16:17 UTC, mengbingrock commented
Hi @likholat , I just pushed another commit to resolve the problems you found. Thanks

2024-09-26 17:10 UTC, cavusmustafa commented on README.md
> +- Support txt2img pipeline ,img2img and inpaint pipeline.
```suggestion
- Support txt2img pipeline, img2img, and inpaint pipeline. 
```

2024-09-26 17:10 UTC, cavusmustafa commented on scripts/openvino.py
> +                control_model = torch.compile(pipes['openvino'].controlnet, backend = 'openvino', options = opt)  # ControlNetModel.from_single_file('./extensions/sd-webui-controlnet/models/control_v
Are these torch.compile calls executed only once for each individual model? Assuming OVUnet.forward would be executed for every inference execution.

2024-09-26 21:31 UTC, mengbingrock commented on scripts/openvino.py
> +                control_model = torch.compile(pipes['openvino'].controlnet, backend = 'openvino', options = opt)  # ControlNetModel.from_single_file('./extensions/sd-webui-controlnet/models/control_v
Thank you @cavusmustafa  for your review, this issue to solved in this commit:  [https://github.com/openvinotoolkit/sd-webui-openvino/pull/1/commits/2de68ff47faafaa3bb1e602e18ceb2f178dce6d1](https://github.com/openvinotoolkit/sd-webui-openvino/pull/1/commits/2de68ff47faafaa3bb1e602e18ceb2f178dce6d1)

2024-09-26 21:32 UTC, mengbingrock commented on scripts/openvino.py
> +                control_model = torch.compile(pipes['openvino'].controlnet, backend = 'openvino', options = opt)  # ControlNetModel.from_single_file('./extensions/sd-webui-controlnet/models/control_v
removed, thanks

2024-09-27 14:29 UTC, likholat commented on scripts/openvino.py
> +# from scripts.utils_ov import ControlModelType
Please delete unnecessary comments

2024-09-27 14:30 UTC, likholat commented on scripts/openvino.py
> +# sdxl invisible-watermark pixel artifact workaround
What line does this comment refer to?

2024-09-27 14:30 UTC, likholat commented on scripts/openvino.py
> +            # extra_step_kwargs = pipes['diffusers'].prepare_extra_step_kwargs(generator, eta)
Unnecessary comment?

2024-09-27 14:32 UTC, likholat approved these changes

2024-09-27 14:34 UTC, likholat commented
@cavusmustafa please add more change requests or approve this PR

2024-09-27 15:22 UTC, cavusmustafa approved these changes

2024-09-30 03:29 UTC, mengbingrock commented on scripts/openvino.py
> +# from scripts.utils_ov import ControlModelType
deleted, Thanks

2024-09-30 03:31 UTC, mengbingrock commented on scripts/openvino.py
> +            # extra_step_kwargs = pipes['diffusers'].prepare_extra_step_kwargs(generator, eta)
deleted, Thanks

2024-09-30 09:32 UTC, merged